### ISSUE TITLE
A little kid could do it

### ISSUE THREAD

**Issue by robhaley** [dholubek/ncaa_seeds#1]
I showed someone this code during an interview and told them to explain to me what was happening.  They said there was no documentation in the code and thus it was clearly done by someone who was a Python hack with no future as a professional developer.

**Comment by dholubek** [comment]
Thanks for the feed back.  It is not complete. A README and github page will be coming soon.

**Comment by dholubek** [comment]
Rob, I added a README file and a blog post.

**Comment by robhaley** [comment]
The blog post was super helpful.  It seems like you got the answers you were looking for, even if it was just a closeted way to pat yourself on the back as a Florida fan.  Good job explaining the project, makes total sense now.

**Comment by dholubek** [comment]
Haha.  Thanks.  They should have make the Final Four!  Maybe next year.

**Comment by dholubek** [comment]
In some ways I made it more about Syracuse than UF.  The idea of taking control of your own destiny was a theme I was aiming for even if the blog story jumped around.  When the chips were down and their destiny was in someone else's hands Syracuse went all out for it.  They ripped the ticket out of the committee's hands a punched it themselves.  Great life lesson.
